# Generated by Django 2.0.2 on 2018-03-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0002_auto_20180310_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
    ]
