"""
Django settings for donationcoordinator project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

import dj_database_url
import django_heroku


def load_env_file(path):
    """load environment file."""

    print("About to load envfile located here:" + path)

    if os.path.exists(path):
        f = open(path, 'r')

        for line in f:
            line = line.replace('\r', '').replace('\n', '')
            if '=' in line:
                lines = line.split("=")
                key = lines[0]
                val = lines[1]

                if key not in os.environ:
                    print(f"'{key}' not in os.environ, but it is inside of '{path}'!")
                    os.environ[key] = val
        f.close()
    else:
        print("File doesn't exist!")


class YouDidntSetYourEnvironmentVarsBro(Exception):
    def __init__(self, m):
        self.missingVar = m

    def __str__(self):
        return f"You gotta set the {self.missingVar} var!"

    def __repr__(self):
        return str(self)


REQUIRED_ENVIRONMENT_VARIABLES = [
    'SECRET_KEY',
    'OSGEO4W_ROOT',
    'GDAL_LIBRARY_PATH',
    'GEOS_LIBRARY_PATH',
    'GDAL_DATA',
    'PROJ_LIB',
    'GEOPOSITION_GOOGLE_MAPS_API_KEY',
]

env_files = [
    'environment.env',
    'secretkey.password.env',
]

for file in env_files:
    load_env_file(file)

for ev in REQUIRED_ENVIRONMENT_VARIABLES:
    if ev not in os.environ:
        print(YouDidntSetYourEnvironmentVarsBro(ev))

# Build paths inside the project like this: os.path.join(PROJECT_ROOT, ...)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_DIR = PROJECT_ROOT

# setup for GDAL, GEOS, etc.
if 'OSGEO4W_ROOT' in os.environ:
    OSGEO4W = os.environ['OSGEO4W_ROOT']
    os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']
    os.environ['PATH'] = OSGEO4W + r"\lib;" + os.environ['PATH']

GDAL_LIBRARY_PATH = os.getenv('GDAL_LIBRARY_PATH')
GEOS_LIBRARY_PATH = os.getenv('GEOS_LIBRARY_PATH')

GEOPOSITION_GOOGLE_MAPS_API_KEY = os.environ.get('GEOPOSITION_GOOGLE_MAPS_API_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') if 'SECRET_KEY' in os.environ else 'supersecret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_extensions',
    'django_activeurl',
    'annoying',
    'donationcoordinator',
    'donator',
    'org',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'donationcoordinator.urls'

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
)


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_ROOT, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'donationcoordinator.wsgi.application'

if 'DATABASE_URL' in os.environ:  # please help me heroku gods
    if 'postgres' in os.environ['DATABASE_URL']:
        os.environ['DATABASE_URL'] = os.environ['DATABASE_URL'].replace('postgres', 'postgis')

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default="postgis://geodjango:geodjango@localhost/geodjango",
        engine='django.contrib.gis.db.backends.postgis',
    ),
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'donator.User'

LOGIN_REDIRECT_URL = '/donator/'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')

MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = ''

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join('static'),
)

# Activate Django-Heroku.
django_heroku.settings(locals())
